name: easy_wallet_v2
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State
  provider: ^6.0.4
  # Cache
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11

  # Localization
  easy_localization: ^3.0.1

  # Utility
  uuid: ^3.0.6
  lottie: ^1.4.3
  syncfusion_flutter_charts: ^20.3.52
  cupertino_icons: ^1.0.2
  animate_do: ^3.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.0
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo/
    - assets/translations/

  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
